### ISSUE TITLE
Getting weird results from screen

### ISSUE THREAD

**Issue by cheapjack** [cefn/avatap#4]
Not sure what to expect from the `integration_main.py`
On power up
![screen2](https://cloud.githubusercontent.com/assets/128456/25355842/f5263f0e-292f-11e7-8faa-9136564a96ea.png)

Ive wired everything like this
```
Screen
Left to Right when screen flipped and in install position with gamebox upright
        * BLK   - GND                   - Backlight Cathode
        * BLA   - 5V                    - Backlight Anode
        * RST   - 5V                    - resetDisplay
        * PSB   - GND                   - Activate SPI
        * E     - GPIO14 (Cockle pin D5)  - SPI Clock
        * RW    - GPIO13 (Cockle pin D7)  - SPI MOSI  
        * RS    - GPIO15 (Cockle pin D8)  - Chip select ?
        * V0    - 5V                    - LCD contrast
        * VCC   - 5V                    - USB power VIN (not 3V3)
        * GND   - 0V                   - Ground
RFID Reader
        * SDA        Cockle Pin D5 GPIO14 (shared with SPI Screen)
        * SCK        Cockle Pin D3  GPIO0
        * MOSI      Cockle Pin D4  GPIO2
        * MISO      Cockle Pin D2 GPIO4
        * GND      Ground
        * RST       Cockle Pin D1 GPIO5
        * 3V3        3V3
```
and file system on cockle is
```
mfrc522.py
st7920.py
bitfont.py
faces
main.py
```
with 
`font_5x7.py` in the faces/ dir

dont seem to get any response by read but I can see screen doing stuff over serial.
If I try to do stuff with the example code in the st7920 repo and get this
![screen3](https://cloud.githubusercontent.com/assets/128456/25355941/5b60fd04-2930-11e7-9c87-c34997e8175f.png)

**Comment by cheapjack** [comment]
tested the example read and write [from here](https://github.com/wendlers/micropython-mfrc522) so card reader working fine... must be my wiring...

**Comment by cefn** [comment]
The wiring I have for the screen in the direction from pin 1 to pin 20 is...
```
GND -> 0V
VCC -> 5V (USB power, coming from VIN)
V0 -> Center Pin of Contrast Potentiometer - as it's at full rotation this is equivalent to 5V
RS - >  Cockle D8 (ESP8266 GPIO 15 )
R/W -> Cockle D7 (ESP8266 GPIO 13)
E -> Cockle D5 (ESP8266 GPIO 14)
PSB -> 0V
RST -> 5V
BLA _> 5V
BLK -> 0V
```

Try pulling the latest from https://github.com/ShrimpingIt/micropython-st7920 as it now has tested logic for slaveSelectPin (previously I was just wiring it directly to 5V if I recall).

**Comment by cefn** [comment]
I've updated the comment above to include the card wiring.

**Comment by cheapjack** [comment]
result! success after a pull. I'd not pulled for a while!!

**Comment by cheapjack** [comment]
results as expected now. Wiring confirmed
